riak-suanpan-pb:
  discovery:
    method: consul
    service: riak-suanpan-pb
  haproxy:
    options:
      - bind *:3200
      - mode tcp
      - balance leastconn
    server_options: check inter 10000 rise 3 fall 2

riak-quality-http:
  discovery:
    method: consul
    service: riak-quality-http
  haproxy:
    options:
      - bind *:3201
      - mode http
      - balance roundrobin
    server_options: check inter 10s rise 3 fall 2

ads-thrift:
  discovery:
    method: consul
    service: ads-thrift
  haproxy:
    options:
      - bind *:3202
      - mode tcp
      - balance leastconn
    server_options: check inter 10000 rise 3 fall 2

gateway-http:
  discovery:
    method: consul
    service: gateway-http
  haproxy:
    options:
      - bind *:3203
      - mode http
      - balance roundrobin
    server_options: check inter 10s rise 3 fall 2
